### ISSUE TITLE
dropdown does not toggle shut on touch

### ISSUE THREAD

**Issue by rsbondi** [cognitom/riot-bootstrap#2]
I would expect this to work the same as the mouse click, but it toggles closed and reopens immediately.

**Comment by rsbondi** [comment]
I cloned this in and it appears to work, maybe just need to [update](http://cognitom.github.io/riot-bootstrap/)

EDIT: it works on my linux/win/ff but not in win/chrome, I get a blank page in ie, probably need the shim/shiv

**Comment by cognitom** [comment]
@rsbondi thanks for your feedback!
I've just update it to riot-bootstrap v0.2.0, so the second problem has been solved :)

I'll check the dropdown issue.
