### ISSUE TITLE
Scope emulation is good or not?

### ISSUE THREAD

**Issue by cognitom** [cognitom/riot-bootstrap#3]
Hi, guys!

Currently, Riot.js (v2.0.15) doesn't support parent scopes in transclusion ([see detail](https://github.com/muut/riotjs/issues/300#issuecomment-96066358)).
But it feels unpractically inconvenient in component libraries like `riot-bootstrap`. For example:

``` html
<section>
  <btn-group>
    <btn onpush={ parent.parent.pushL }>Left</btn>
    <btn onpush={ parent.parent.pushM }>Middle</btn>
    <btn onpush={ parent.parent.pushR }>Right</btn>
  </btn-group>
  <p class="comment">{ parent.parent.comment }</p>
</section>
pushL (e) {
  this.comment = 'Left button was clicked.'
  this.update() // this line is needed because the event would be fired in the child.
}
```

`parent.parent.x` seems unacceptable for me. And there's many inconsistencies compared to normal tags.

So I've tried to make `riot-bootstrap` emulate the scope. But it's dirty and has some difficult points. How do you think?
- [load parent variables](https://github.com/cognitom/riot-bootstrap/blob/v0.2.0/components/btn.html#L37) (the child's variables have priority)
- [update the variables from parent](https://github.com/cognitom/riot-bootstrap/blob/v0.2.0/components/btn.html#L43) on each `update` event
- [automatically update the parent](https://github.com/cognitom/riot-bootstrap/blob/v0.2.0/components/btn.html#L22) (or its parent, depends on the situation)

The entire code is here: https://github.com/cognitom/riot-bootstrap/blob/master/components/btn.html

**Comment by cognitom** [comment]
How about? @jmas @rsbondi @eyy @txchen
Any feedback is welcome. Thanks.

**Comment by rsbondi** [comment]
At a quick glance, I don't think you need `initProperties`

``` javascript
    loadParentProperties () {
      for (var k in this.parent)
        if (!(k in this))
          this[k] = this.parent[k]
    }
```

and for `updateCaller` look [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/keys)

**Comment by cognitom** [comment]
Oops, I had mistake. [I've slightly updated](https://github.com/cognitom/riot-bootstrap/blob/master/components/btn.html#L26) `updateCaller`. Thanks @rsbondi.

**Comment by rsbondi** [comment]
why not do this and get rid of `initProperties`?  I can't imagine there is much overhead getting the keys this way.

``` javascript
    updateCaller (f) {
      var  keys =  Object.keys(this.parent).
      for (var i = 0; i < keys.length; i++)
        if (this.parent[keys[i]] === f) {
          this.parent.update()
          return
        }
      if (this.parent.updateCaller) this.parent.updateCaller(f)
    }
```

although I am not sure what this loop does, should be equivalent.

**Comment by cognitom** [comment]
`initProperties` is need to know which method is in the same scope. So this should be called before `loadParentProperties`. And `loadParentProperties` would be called on each `update` event.

Yeah, the code of this loop is little bit unclear. What I wanted to do is just determine the caller of `opts.xxxx` method. I have an assumption that `opts.xxx` should be a method of `Tag` (parent's or grand-parent's or....), so `this.parent[keys[i]] === f` is determining the scope of `opts.xxx`.

**Comment by rsbondi** [comment]
Now I understand, once you set the parent property, the child has it.  My apologies

Here is my attempt to redeem myself.

``` javascript
var scopemix = {
  initProperties: function(f) {
    this._ownPropKeys = []
    for (var k in this) if (this[k]) this._ownPropKeys[k] = true
  },
  updateCaller: function(f) {
    var keys = []
    for (var k in this.parent._ownPropKeys || this.parent) keys.push(k)
    for (var i = 0; i < keys.length; i++)
      if (this.parent[keys[i]] === f) {
        this.parent.update()
        return
      }
    if (this.parent && this.parent.updateCaller) this.parent.updateCaller(f)
  },
  loadParentProperties: function() {
    for (var k in this.parent)
      if (!this._ownPropKeys[k])
        this[k] = this.parent[k]
  }
}

...

riot.tag('btn-group', '<yield></yield>', 'btn-group ...}', function(opts) {

  this.mixin(scopemix)
  this.initProperties()
  this.on('update', this.loadParentProperties)

});
```

I did this with the `brn` and `btn-group`, using riot dev branch build and the label updates on the demo.  Of course, it is not yet available, but probably worth a look at this upcoming feature

cc: @emehrkay

**Comment by cognitom** [comment]
Cool!!

**Comment by cognitom** [comment]
I've added `dev` branch to try Riot's mixin feature.
https://github.com/cognitom/riot-bootstrap/blob/dev/mixins/parent-scope.js

These codes are simply [concatenated](https://github.com/cognitom/riot-bootstrap/blob/dev/gulpfile.coffee#L37) into one file.
- `if (!window.mixin) var mixin = {};`
- [mixins](https://github.com/cognitom/riot-bootstrap/tree/dev/mixins)
- [tags](https://github.com/cognitom/riot-bootstrap/tree/dev/components)

I feel we may need the standard way to define mixins. (I'm not sure the way above is the best)

**Comment by rsbondi** [comment]
I think [this](https://github.com/cognitom/riot-bootstrap/blob/dev/components/btn-group.html#L8) could be moved to `initProperties` of the mixin?

**Comment by cognitom** [comment]
Yeah, that's right. Thank you.

**Comment by nevf** [comment]
+1 I agree about parent scopes being awkward to work with and like what you've done here.

**Comment by cognitom** [comment]
I'm closing this issue, because we've been discussing about it on `riot/riot`.
