### ISSUE TITLE
What's the best way to make it compatible with browser/browserify?

### ISSUE THREAD

**Issue by cognitom** [cognitom/riot-bootstrap#4]
@rsbondi has [reported](https://github.com/muut/riotjs/pull/699#issuecomment-101003498) that it doesn't work in browser. [This line](https://github.com/cognitom/riot-bootstrap/blob/dev/mixins/parent-scope.js#L10):

``` javascript
var riot = (!window || !window.riot) ? require('riot') : window.riot
```

Is there any good solution? Thanks.

**Comment by rsbondi** [comment]
It is [working](http://plnkr.co/edit/pa7WAq?p=preview) now, not sure at what point it did not work or why.

**Comment by cognitom** [comment]
I see. I'm closing this once. If you see it again, feel free to re-open it :)
