### ISSUE TITLE
Overlay mixin?

### ISSUE THREAD

**Issue by tomeraz** [cognitom/riot-bootstrap#5]
Any plans for a modal component + overlay mixin?
Like this one:
[React Bootstrap Modal](http://react-bootstrap.github.io/components.html#modals)
which is based on
[OverlayMixin?](https://github.com/react-bootstrap/react-bootstrap/blob/v0.11.1/src/OverlayMixin.js)

**Comment by cognitom** [comment]
I'm not sure at this point. But PR is always welcome :)
FYI @gregorypratt has started new project 'RiotGear' and he's already implemented the overlay in `rg-modal`.
https://github.com/RiotGear/rg-modal/
