### ISSUE TITLE
Download zip for dev branch

### ISSUE THREAD

**Issue by nevf** [cognitom/riot-bootstrap#6]
Hi, I'd like to download the zip file for the dev bracnh https://github.com/cognitom/riot-bootstrap/tree/dev but the link is to the main branch.

FYI I've been using Bootstrap for quite a while, however I am very, very new to Riot. Many thanks for your efforts with riot-bootstrap.

**Comment by cognitom** [comment]
Now I've just merged `dev` into `master`. Try again :)
If you have interest to try or commit `dev`, use `git` command. Thanks.
