### ISSUE TITLE
<style scoped> only works in FF

### ISSUE THREAD

**Issue by nevf** [cognitom/riot-bootstrap#8]
From my reading `<style scoped>` is only supported by Firefox. The Demo does work in Chrome, which may simply be ignoring the `scoped` keyword.

**Comment by rsbondi** [comment]
riot does its own scoping replacing `selector {...}` with `my-tag selector {...}`

**Comment by nevf** [comment]
@rsbondi Thanks for that, definitely good to know. 

Slight change of discussion. If you use `<style scoped>` then I assume higher level CSS used to specify themes won't work. ie. the "danger" color for all Riot Bootstrap Tags.

**Comment by cognitom** [comment]
At this time, `riot-bootstrap` is providing no way to customise the theme. But this code works:

``` css
btn button[data-option="danger"] { background-color: red }
```

Theming seems an interest issue. Feel free to open a new one :)
